[default]
python-interpreter-path = "c:\\Sudo_Hatter_Command\\Projects\\B&L WorldWide\\.venv\\Scripts\\python.exe"
search_path = [
    "c:\\Sudo_Hatter_Command\\Projects\\B&L WorldWide",
    "c:\\Sudo_Hatter_Command\\Projects\\B&L WorldWide\\.venv\\Lib\\site-packages"
]
project_includes = ["backend/**/*.py"]
site_package_path = "c:\\Sudo_Hatter_Command\\Projects\\B&L WorldWide\\.venv\\Lib\\site-packages"
